### PR TITLE
Switch to uv

### PR DESCRIPTION
**Pull request by blu-nitro**
Switch to `uv`, which is a much faster alternative to `pipenv`.
This also fixes dependabot false warnings, as we did never really use the `Pipfile.lock` and this PR removes it.

### CODE REVIEW

**Review by robin-nitrokey — COMMENTED** [review]
Looks good!  It would make sense to also use `uv pip compile` / `uv pip sync` to pin the dependencies as we previously did with `pipenv`.  What do you think?

**Comment by blu-nitro** [comment]
> It would make sense to also use `uv pip compile` / `uv pip sync` to pin the dependencies as we previously did with `pipenv`

We never actually did that, as we used `pipenv install`, which ignores `Pipfile.lock` and instead rebuilds it every time. 
That's why i didn't bother with it here, but it could be something we add in the future.

**Review by robin-nitrokey — APPROVED** [review]
Ah, I see.  Then please crate an issue for that once this PR is merged.

Out of curiosity, do you know what is the requirement for a command to be callable via `uv tool`?

**Comment by blu-nitro** [comment]
> Out of curiosity, do you know what is the requirement for a command to be callable via `uv tool`?

A tool to be run with `uv tool run` needs to be installable as i recall, but i'm not sure why this was not possible for mypy. This feature is quite new and the documentation did not really exist when i last looked, so i just went with it where it worked tbh.

**Pull request merged**
